"""Constants for the Daikin Altherma integration."""

DOMAIN = "daikin_altherma"
TIMEOUT = 60
MIN_TIME_BETWEEN_UPDATES_SECONDS = 5
UPDATE_INTERVAL_SECONDS = 2
ASYNC_UPDATE_TIMEOUT_SECONDS = 10
MAX_UPDATE_FAILED = -1

